ALTER TABLE items ADD COLUMN container INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN opened INTEGER NOT NULL DEFAULT 1;
ALTER TABLE items ADD COLUMN locked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN locked_by_item_id TEXT;
