/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiStreamCommandRouteImport } from './routes/api/stream-command'
import { Route as AdminWorldIdRouteImport } from './routes/admin/$worldId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamCommandRoute = ApiStreamCommandRouteImport.update({
  id: '/api/stream-command',
  path: '/api/stream-command',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorldIdRoute = AdminWorldIdRouteImport.update({
  id: '/admin/$worldId',
  path: '/admin/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/$worldId': typeof AdminWorldIdRoute
  '/api/stream-command': typeof ApiStreamCommandRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$worldId': typeof AdminWorldIdRoute
  '/api/stream-command': typeof ApiStreamCommandRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/$worldId': typeof AdminWorldIdRoute
  '/api/stream-command': typeof ApiStreamCommandRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/$worldId' | '/api/stream-command' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/$worldId' | '/api/stream-command' | '/admin'
  id: '__root__' | '/' | '/admin/$worldId' | '/api/stream-command' | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminWorldIdRoute: typeof AdminWorldIdRoute
  ApiStreamCommandRoute: typeof ApiStreamCommandRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-command': {
      id: '/api/stream-command'
      path: '/api/stream-command'
      fullPath: '/api/stream-command'
      preLoaderRoute: typeof ApiStreamCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$worldId': {
      id: '/admin/$worldId'
      path: '/admin/$worldId'
      fullPath: '/admin/$worldId'
      preLoaderRoute: typeof AdminWorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminWorldIdRoute: AdminWorldIdRoute,
  ApiStreamCommandRoute: ApiStreamCommandRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
