// AUTO-GENERATED by scripts/parse-world.ts. Do not edit by hand.

export const BURNING_DISTRICT = {
  "locations": [
    {
      "id": "loc_flaming_goblet",
      "label": "The Flaming Goblet",
      "shortDescription": "A tavern on the edge of the Burning District",
      "longDescription": "A tavern with one wall constantly aflame, mostly staffed by Tieflings. The heat inside is intense."
    },
    {
      "id": "loc_burning_street",
      "label": "Burning Street",
      "shortDescription": "A street engulfed in perpetual flames",
      "longDescription": "Once a bustling street, now consumed by magical fire that cannot be extinguished."
    },
    {
      "id": "loc_fire_salvagers",
      "label": "Fire Salvagers' Camp",
      "shortDescription": "A makeshift camp of scavengers",
      "longDescription": "A settlement of survivors who have adapted to life in the Burning District, trading in salvaged goods."
    },
    {
      "id": "loc_zezrans_house",
      "label": "Zezran's House",
      "shortDescription": "A partially burned wizard's house",
      "longDescription": "The former residence of the wizard Zezran, now a dangerous ruin with flames licking at its walls."
    },
    {
      "id": "loc_workshop",
      "label": "Zezran's Workshop",
      "shortDescription": "A cluttered magical workshop",
      "longDescription": "The heart of Zezran's experiments, filled with arcane equipment and magical artifacts."
    },
    {
      "id": "loc_inferno_alley",
      "label": "Inferno Alley",
      "shortDescription": "A narrow alley of intense heat",
      "longDescription": "A tight passage where the flames burn hottest, challenging even the most fire-resistant adventurers."
    },
    {
      "id": "loc_elemental_plaza",
      "label": "Elemental Plaza",
      "shortDescription": "A wide open area with a fire elemental",
      "longDescription": "A former city square now dominated by a massive fire elemental, believed to be the mother of the trapped elementals."
    },
    {
      "id": "loc_ember_avenue",
      "label": "Ember Avenue",
      "shortDescription": "A wide street with floating embers",
      "longDescription": "A broad avenue where glowing embers float through the air like fireflies, creating a beautiful yet dangerous spectacle."
    },
    {
      "id": "loc_ash_lane",
      "label": "Ash Lane",
      "shortDescription": "A street covered in deep ash",
      "longDescription": "A narrow lane where ash has accumulated to knee-depth, making movement difficult and hiding potential dangers."
    },
    {
      "id": "loc_phoenix_row",
      "label": "Phoenix Row",
      "shortDescription": "A street of colorful, flickering flames",
      "longDescription": "A street where flames dance in vibrant colors reminiscent of a phoenix's plumage, constantly dying and being reborn."
    },
    {
      "id": "loc_smoldering_square",
      "label": "Smoldering Square",
      "shortDescription": "An open area with smoldering ruins",
      "longDescription": "A once-bustling marketplace, now a large square filled with the smoldering remains of stalls and buildings."
    },
    {
      "id": "loc_dockside_markets",
      "label": "Dockside Markets",
      "shortDescription": "A bustling marketplace near the docks",
      "longDescription": "A lively area where traders and sailors mingle, selling goods from distant lands. The smell of salt and spices fills the air."
    },
    {
      "id": "loc_docks",
      "label": "The Docks",
      "shortDescription": "A series of wooden piers extending into the water",
      "longDescription": "Wooden piers stretch out into the water, where ships of various sizes are moored. Captain Serena's crew can be seen patrolling near their ship, eyeing strangers suspiciously."
    },
    {
      "id": "loc_serenas_ship",
      "label": "The Serpent",
      "shortDescription": "Captain Serena's impressive ship",
      "longDescription": "A sleek vessel with intricate carvings of serpents along its hull. Currently undergoing repairs, but still looks formidable."
    },
    {
      "id": "loc_captains_cabin",
      "label": "Captain's Cabin",
      "shortDescription": "Captain Serena's private quarters",
      "longDescription": "A luxurious cabin filled with maps, navigational instruments, and exotic treasures. The air is heavy with the scent of spices and sea salt."
    },
    {
      "id": "loc_crews_quarters",
      "label": "Crew's Quarters",
      "shortDescription": "The living space for Captain Serena's crew",
      "longDescription": "A cramped area below deck filled with hammocks, personal belongings, and the strong smell of unwashed sailors."
    }
  ],
  "exits": [
    {
      "id": "exit_to_street",
      "from": "loc_flaming_goblet",
      "to": "loc_burning_street",
      "direction": "north",
      "label": "Tavern Back Door",
      "locked": true,
      "lockedByItem": null
    },
    {
      "id": "exit_to_tavern",
      "from": "loc_burning_street",
      "to": "loc_flaming_goblet",
      "direction": "south",
      "label": "Tavern Back Entrance",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_markets",
      "from": "loc_flaming_goblet",
      "to": "loc_dockside_markets",
      "direction": "south",
      "label": "Tavern Front Door",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_tavern_from_markets",
      "from": "loc_dockside_markets",
      "to": "loc_flaming_goblet",
      "direction": "north",
      "label": "Tavern Front Entrance",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_camp",
      "from": "loc_burning_street",
      "to": "loc_fire_salvagers",
      "direction": "east",
      "label": "Path to Salvagers' Camp",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_house",
      "from": "loc_burning_street",
      "to": "loc_zezrans_house",
      "direction": "west",
      "label": "Zezran's House",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_workshop",
      "from": "loc_zezrans_house",
      "to": "loc_workshop",
      "direction": "down",
      "label": "Hidden Passage",
      "locked": true,
      "lockedByItem": null
    },
    {
      "id": "exit_to_alley",
      "from": "loc_burning_street",
      "to": "loc_inferno_alley",
      "direction": "north",
      "label": "Narrow Alleyway",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_plaza",
      "from": "loc_inferno_alley",
      "to": "loc_elemental_plaza",
      "direction": "east",
      "label": "Wide Street",
      "locked": true,
      "lockedByItem": null
    },
    {
      "id": "exit_to_ember",
      "from": "loc_burning_street",
      "to": "loc_ember_avenue",
      "direction": "northeast",
      "label": "Glowing Archway",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_ash",
      "from": "loc_ember_avenue",
      "to": "loc_ash_lane",
      "direction": "east",
      "label": "Ashen Path",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_phoenix",
      "from": "loc_ash_lane",
      "to": "loc_phoenix_row",
      "direction": "south",
      "label": "Colorful Flames",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_square",
      "from": "loc_phoenix_row",
      "to": "loc_smoldering_square",
      "direction": "west",
      "label": "Crumbling Archway",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_burning",
      "from": "loc_smoldering_square",
      "to": "loc_burning_street",
      "direction": "north",
      "label": "Flame-Licked Street",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_docks",
      "from": "loc_dockside_markets",
      "to": "loc_docks",
      "direction": "east",
      "label": "Path to Docks",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_markets_from_docks",
      "from": "loc_docks",
      "to": "loc_dockside_markets",
      "direction": "west",
      "label": "Path to Markets",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_serenas_ship",
      "from": "loc_docks",
      "to": "loc_serenas_ship",
      "direction": "south",
      "label": "Gangplank to The Serpent",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_docks_from_ship",
      "from": "loc_serenas_ship",
      "to": "loc_docks",
      "direction": "north",
      "label": "Gangplank to Docks",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_burning_from_camp",
      "from": "loc_fire_salvagers",
      "to": "loc_burning_street",
      "direction": "west",
      "label": "Camp Exit",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_burning_from_house",
      "from": "loc_zezrans_house",
      "to": "loc_burning_street",
      "direction": "east",
      "label": "House Entrance",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_house_from_workshop",
      "from": "loc_workshop",
      "to": "loc_zezrans_house",
      "direction": "up",
      "label": "Workshop Up",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_burning_from_alley",
      "from": "loc_inferno_alley",
      "to": "loc_burning_street",
      "direction": "south",
      "label": "Alley Exit",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_alley_from_plaza",
      "from": "loc_elemental_plaza",
      "to": "loc_inferno_alley",
      "direction": "west",
      "label": "Plaza Exit",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_burning_from_ember",
      "from": "loc_ember_avenue",
      "to": "loc_burning_street",
      "direction": "southwest",
      "label": "Ember Avenue Exit",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_ember_from_ash",
      "from": "loc_ash_lane",
      "to": "loc_ember_avenue",
      "direction": "west",
      "label": "Ash Lane Exit",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_ash_from_phoenix",
      "from": "loc_phoenix_row",
      "to": "loc_ash_lane",
      "direction": "north",
      "label": "Phoenix Row Exit",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_phoenix_from_square",
      "from": "loc_smoldering_square",
      "to": "loc_phoenix_row",
      "direction": "east",
      "label": "Smoldering Square Exit",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_captains_cabin",
      "from": "loc_serenas_ship",
      "to": "loc_captains_cabin",
      "direction": "south",
      "label": "Captain's Cabin Door",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_ship_from_cabin",
      "from": "loc_captains_cabin",
      "to": "loc_serenas_ship",
      "direction": "north",
      "label": "Cabin Exit",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_crews_quarters",
      "from": "loc_serenas_ship",
      "to": "loc_crews_quarters",
      "direction": "down",
      "label": "Hatch to Crew's Quarters",
      "locked": false,
      "lockedByItem": null
    },
    {
      "id": "exit_to_ship_from_quarters",
      "from": "loc_crews_quarters",
      "to": "loc_serenas_ship",
      "direction": "up",
      "label": "Ladder to Deck",
      "locked": false,
      "lockedByItem": null
    }
  ],
  "items": [
    {
      "id": "item_phoenix_heart",
      "label": "The Phoenix Heart",
      "shortDescription": "Source of the district's eternal flames. Pyra (`char_47802`) desperately wants it.",
      "longDescription": "Source of the district's eternal flames. Pyra (`char_47802`) desperately wants it.",
      "ownerKind": "location",
      "ownerId": "loc_workshop",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_rusty_key",
      "label": "Rusty Key",
      "shortDescription": "Opens the back door of the Flaming Goblet.",
      "longDescription": "Opens the back door of the Flaming Goblet.",
      "ownerKind": "item",
      "ownerId": "item_wooden_box",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_wooden_box",
      "label": "Wooden Box",
      "shortDescription": "Contains the Rusty Key.",
      "longDescription": "Contains the Rusty Key.",
      "ownerKind": "location",
      "ownerId": "loc_flaming_goblet",
      "weight": 1,
      "hidden": true
    },
    {
      "id": "item_fire_extinguisher",
      "label": "Magical Fire Extinguisher",
      "shortDescription": "Uncle Bob (`char_62103`) is terrified of this and will flee if he sees it.",
      "longDescription": "Uncle Bob (`char_62103`) is terrified of this and will flee if he sees it.",
      "ownerKind": "agent",
      "ownerId": "char_39322",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_zezrans_journal",
      "label": "Zezran's Journal",
      "shortDescription": "Crucial info about the Phoenix Heart's creation and weaknesses.",
      "longDescription": "Crucial info about the Phoenix Heart's creation and weaknesses.",
      "ownerKind": "location",
      "ownerId": "loc_zezrans_house",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_frostfire_bomb",
      "label": "Frostfire Bomb",
      "shortDescription": "Extremely effective against Inferna (`char_59731`).",
      "longDescription": "Extremely effective against Inferna (`char_59731`).",
      "ownerKind": "location",
      "ownerId": "loc_fire_salvagers",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_flame_tongs",
      "label": "Flame Tongs",
      "shortDescription": "Can safely handle the Phoenix Heart.",
      "longDescription": "Can safely handle the Phoenix Heart.",
      "ownerKind": "agent",
      "ownerId": "char_91245",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_elemental_jar",
      "label": "Elemental Containment Jar",
      "shortDescription": "Can capture Ember (`char_70451`) or other small fire elementals.",
      "longDescription": "Can capture Ember (`char_70451`) or other small fire elementals.",
      "ownerKind": "location",
      "ownerId": "loc_workshop",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_ashen_chronicle",
      "label": "Ashen Chronicle",
      "shortDescription": "Records memories of those who touch it.",
      "longDescription": "Records memories of those who touch it.",
      "ownerKind": "agent",
      "ownerId": "char_28934",
      "weight": 2,
      "hidden": false
    },
    {
      "id": "item_cinder_coins",
      "label": "Cinder Coins",
      "shortDescription": "Currency of the Burning District.",
      "longDescription": "Currency of the Burning District.",
      "ownerKind": "location",
      "ownerId": "loc_smoldering_square",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_ember_whistle",
      "label": "Ember Whistle",
      "shortDescription": "Commands nearby embers and small flames.",
      "longDescription": "Commands nearby embers and small flames.",
      "ownerKind": "agent",
      "ownerId": "char_70451",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_fire_map",
      "label": "Fire Map",
      "shortDescription": "Real-time map of fires in the district.",
      "longDescription": "Real-time map of fires in the district.",
      "ownerKind": "location",
      "ownerId": "loc_flaming_goblet",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_heat_cloak",
      "label": "Heat-Resistant Cloak",
      "shortDescription": "Protects against extreme heat.",
      "longDescription": "Protects against extreme heat.",
      "ownerKind": "location",
      "ownerId": "loc_fire_salvagers",
      "weight": 2,
      "hidden": false
    },
    {
      "id": "item_phoenix_feather",
      "label": "Phoenix Feather",
      "shortDescription": "Inferna is drawn to it.",
      "longDescription": "Inferna is drawn to it.",
      "ownerKind": "location",
      "ownerId": "loc_phoenix_row",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_captains_log",
      "label": "Captain's Log",
      "shortDescription": "Info about Serena's encounters with water elementals.",
      "longDescription": "Info about Serena's encounters with water elementals.",
      "ownerKind": "location",
      "ownerId": "loc_captains_cabin",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_treasure_map",
      "label": "Mysterious Map",
      "shortDescription": "Hidden in a secret compartment in Serena's desk.",
      "longDescription": "Hidden in a secret compartment in Serena's desk.",
      "ownerKind": "location",
      "ownerId": "loc_captains_cabin",
      "weight": 1,
      "hidden": true
    },
    {
      "id": "item_spyglass",
      "label": "Enchanted Spyglass",
      "shortDescription": "Sees through magical illusions.",
      "longDescription": "Sees through magical illusions.",
      "ownerKind": "location",
      "ownerId": "loc_captains_cabin",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_lucky_coin",
      "label": "Lucky Silver Coin",
      "shortDescription": "Believed to protect the ship.",
      "longDescription": "Believed to protect the ship.",
      "ownerKind": "location",
      "ownerId": "loc_crews_quarters",
      "weight": 1,
      "hidden": false
    },
    {
      "id": "item_smuggled_goods",
      "label": "Smuggled Goods",
      "shortDescription": "Hidden under a loose floorboard.",
      "longDescription": "Hidden under a loose floorboard.",
      "ownerKind": "location",
      "ownerId": "loc_crews_quarters",
      "weight": 1,
      "hidden": true
    },
    {
      "id": "item_crew_manifest",
      "label": "Crew Manifest",
      "shortDescription": "List of crew members and roles.",
      "longDescription": "List of crew members and roles.",
      "ownerKind": "location",
      "ownerId": "loc_crews_quarters",
      "weight": 1,
      "hidden": false
    }
  ],
  "agents": [
    {
      "id": "char_39322",
      "label": "Paff Pinkerton",
      "locationId": "loc_flaming_goblet",
      "hp": 20,
      "damage": 2,
      "defense": 12,
      "capacity": 30,
      "mood": null,
      "goal": null,
      "autonomous": false,
      "shortDescription": "A youth with a fierce determination in his eyes. Nephew of the wizard Bob, he believes his uncle was involved in creating the Burning District and seeks to stop the eternal fire.",
      "longDescription": "A youth with a fierce determination in his eyes. Nephew of the wizard Bob, he believes his uncle was involved in creating the Burning District and seeks to stop the eternal fire."
    },
    {
      "id": "char_84751",
      "label": "Captain Serena",
      "locationId": "loc_serenas_ship",
      "hp": 25,
      "damage": 3,
      "defense": 14,
      "capacity": 10,
      "mood": "Cautious",
      "goal": "Return to the sea",
      "autonomous": false,
      "shortDescription": "A tall tiefling with red skin and sharp horns, wearing a coat of fish scales. Veteran sailor whose ship is undergoing repairs. Has valuable information about Zezran and the elemental plane of water.",
      "longDescription": "A tall tiefling with red skin and sharp horns, wearing a coat of fish scales. Veteran sailor whose ship is undergoing repairs. Has valuable information about Zezran and the elemental plane of water."
    },
    {
      "id": "char_62103",
      "label": "Uncle Bob",
      "locationId": "loc_burning_street",
      "hp": 18,
      "damage": 4,
      "defense": 13,
      "capacity": 10,
      "mood": "Anxious",
      "goal": "Obtain the Phoenix Heart for himself",
      "autonomous": true,
      "shortDescription": "Cantankerous old man in a singed wizard's robe. Former colleague of Zezran, involved in creating the Phoenix Heart and the subsequent burning of the district. Hides a guilty secret.",
      "longDescription": "Cantankerous old man in a singed wizard's robe. Former colleague of Zezran, involved in creating the Phoenix Heart and the subsequent burning of the district. Hides a guilty secret."
    },
    {
      "id": "char_15987",
      "label": "Elysia Everwood",
      "locationId": "loc_fire_salvagers",
      "hp": 22,
      "damage": 2,
      "defense": 13,
      "capacity": 10,
      "mood": "Desperate",
      "goal": "Redeem herself and restore her family's honor",
      "autonomous": false,
      "shortDescription": "Elf with a haunted look, clothes singed and tattered. Last of a renowned elven family, seeking to clear her name.",
      "longDescription": "Elf with a haunted look, clothes singed and tattered. Last of a renowned elven family, seeking to clear her name."
    },
    {
      "id": "char_70451",
      "label": "Ember",
      "locationId": "loc_ember_avenue",
      "hp": 15,
      "damage": 2,
      "defense": 16,
      "capacity": 10,
      "mood": "Playful",
      "goal": "Spread chaos and laughter",
      "autonomous": false,
      "shortDescription": "Small flickering humanoid of living flame. Born from the magical fires; loves tricks and misdirection.",
      "longDescription": "Small flickering humanoid of living flame. Born from the magical fires; loves tricks and misdirection."
    },
    {
      "id": "char_28934",
      "label": "Ashen",
      "locationId": "loc_ash_lane",
      "hp": 35,
      "damage": 4,
      "defense": 15,
      "capacity": 10,
      "mood": "Melancholy",
      "goal": "Preserve the history of the district",
      "autonomous": false,
      "shortDescription": "Humanoid of tightly packed ash with glowing ember eyes. Mourns the lost city.",
      "longDescription": "Humanoid of tightly packed ash with glowing ember eyes. Mourns the lost city."
    },
    {
      "id": "char_53679",
      "label": "Flicker",
      "locationId": "loc_phoenix_row",
      "hp": 20,
      "damage": 2,
      "defense": 14,
      "capacity": 10,
      "mood": "Anxious",
      "goal": "Find a way to control the district's flames",
      "autonomous": false,
      "shortDescription": "Lithe human with hair that shifts between shades of red and orange. Performer with unique fire manipulation.",
      "longDescription": "Lithe human with hair that shifts between shades of red and orange. Performer with unique fire manipulation."
    },
    {
      "id": "char_91245",
      "label": "Cinder",
      "locationId": "loc_smoldering_square",
      "hp": 28,
      "damage": 3,
      "defense": 14,
      "capacity": 10,
      "mood": "Determined",
      "goal": "Rebuild a new community from the ashes",
      "autonomous": false,
      "shortDescription": "Stocky dwarf with soot-stained skin and a smoldering beard. Former smith, now leads salvagers.",
      "longDescription": "Stocky dwarf with soot-stained skin and a smoldering beard. Former smith, now leads salvagers."
    },
    {
      "id": "char_47802",
      "label": "Pyra",
      "locationId": "loc_elemental_plaza",
      "hp": 24,
      "damage": 4,
      "defense": 15,
      "capacity": 10,
      "mood": "Intense",
      "goal": "Harness the power of the Burning District",
      "autonomous": false,
      "shortDescription": "Tall woman with fiery red hair and flickering eyes. Powerful pyromancer.",
      "longDescription": "Tall woman with fiery red hair and flickering eyes. Powerful pyromancer."
    },
    {
      "id": "char_36510",
      "label": "Smolder",
      "locationId": "loc_burning_street",
      "hp": 26,
      "damage": 3,
      "defense": 13,
      "capacity": 10,
      "mood": "Pessimistic",
      "goal": "Find a way to escape the Burning District",
      "autonomous": false,
      "shortDescription": "Muscular human with burn scars and tattered firefighter gear. Believes the district is beyond saving.",
      "longDescription": "Muscular human with burn scars and tattered firefighter gear. Believes the district is beyond saving."
    },
    {
      "id": "char_82367",
      "label": "Ash Pup",
      "locationId": "loc_ash_lane",
      "hp": 12,
      "damage": 1,
      "defense": 15,
      "capacity": 10,
      "mood": "Curious",
      "goal": "Find interesting objects buried in the ash",
      "autonomous": false,
      "shortDescription": "Small dog-like creature of ash and embers, Ashen's loyal companion.",
      "longDescription": "Small dog-like creature of ash and embers, Ashen's loyal companion."
    },
    {
      "id": "char_59731",
      "label": "Inferna",
      "locationId": "loc_elemental_plaza",
      "hp": 60,
      "damage": 6,
      "defense": 18,
      "capacity": 10,
      "mood": "Protective",
      "goal": "Free her children from the Phoenix Heart",
      "autonomous": false,
      "shortDescription": "Massive majestic fire elemental, mother of the trapped elementals. Guards the Phoenix Heart.",
      "longDescription": "Massive majestic fire elemental, mother of the trapped elementals. Guards the Phoenix Heart."
    },
    {
      "id": "char_13498",
      "label": "Spark",
      "locationId": "loc_flaming_goblet",
      "hp": 18,
      "damage": 2,
      "defense": 14,
      "capacity": 10,
      "mood": "Energetic",
      "goal": "Map out all safe routes in the district",
      "autonomous": true,
      "shortDescription": "Young halfling with hair that crackles with static electricity. Swift messenger.",
      "longDescription": "Young halfling with hair that crackles with static electricity. Swift messenger."
    },
    {
      "id": "char_75024",
      "label": "Cinder Golem",
      "locationId": "loc_smoldering_square",
      "hp": 45,
      "damage": 5,
      "defense": 16,
      "capacity": 10,
      "mood": "Stoic",
      "goal": "Protect the fire salvagers",
      "autonomous": false,
      "shortDescription": "Large humanoid of compressed ash and burning embers, created by Cinder.",
      "longDescription": "Large humanoid of compressed ash and burning embers, created by Cinder."
    },
    {
      "id": "char_20876",
      "label": "Flamebeak",
      "locationId": "loc_phoenix_row",
      "hp": 30,
      "damage": 3,
      "defense": 17,
      "capacity": 10,
      "mood": "Majestic",
      "goal": "Inspire hope in the district's inhabitants",
      "autonomous": false,
      "shortDescription": "Magnificent bird with feathers of dancing flames. Symbol of hope.",
      "longDescription": "Magnificent bird with feathers of dancing flames. Symbol of hope."
    },
    {
      "id": "char_fire_hound_01",
      "label": "Fire Hound",
      "locationId": "loc_inferno_alley",
      "hp": 8,
      "damage": 5,
      "defense": 3,
      "capacity": 0,
      "mood": "Aggressive",
      "goal": "Attack intruders",
      "autonomous": false,
      "shortDescription": "A vicious dog-sized creature of living flame and obsidian bone, growling with molten teeth bared.",
      "longDescription": "A vicious dog-sized creature of living flame and obsidian bone, growling with molten teeth bared. Its eyes glow like coals and it guards the alley with mindless aggression."
    },
    {
      "id": "char_ember_wraith_01",
      "label": "Ember Wraith",
      "locationId": "loc_burning_street",
      "hp": 12,
      "damage": 4,
      "defense": 2,
      "capacity": 0,
      "mood": "Malevolent",
      "goal": "Consume all warmth and life",
      "autonomous": false,
      "shortDescription": "A wisp of concentrated heat in roughly humanoid form, flickering between visibility and translucency.",
      "longDescription": "A wisp of concentrated heat in roughly humanoid form, flickering between visibility and translucency. It radiates intense malevolence and attacks any living creature that strays too close."
    }
  ]
} as const;
